
package org.csapi.wsdl.parlayx.ussd.send.v1_0.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.csapi.schema.parlayx.ussd.send.v1_0.local.NamedParameterList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendUssd", targetNamespace = "http://www.csapi.org/wsdl/parlayx/ussd/send/v1_0/interface")
@XmlSeeAlso({
    org.csapi.schema.parlayx.common.v2_1.ObjectFactory.class,
    org.csapi.schema.parlayx.ussd.send.v1_0.local.ObjectFactory.class
})
public interface SendUssd {


    /**
     * 
     * @param codeScheme
     * @param endPoint
     * @param msgType
     * @param receiveCB
     * @param serviceCode
     * @param senderCB
     * @param extenionInfo
     * @param ussdOpType
     * @param msIsdn
     * @param ussdString
     * @return
     *     returns java.lang.String
     * @throws PolicyException
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
    @RequestWrapper(localName = "sendUssd", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", className = "org.csapi.schema.parlayx.ussd.send.v1_0.local.SendUssd")
    @ResponseWrapper(localName = "sendUssdResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", className = "org.csapi.schema.parlayx.ussd.send.v1_0.local.SendUssdResponse")
    public String sendUssd(
        @WebParam(name = "msgType", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        int msgType,
        @WebParam(name = "senderCB", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String senderCB,
        @WebParam(name = "receiveCB", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String receiveCB,
        @WebParam(name = "ussdOpType", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        int ussdOpType,
        @WebParam(name = "msIsdn", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String msIsdn,
        @WebParam(name = "serviceCode", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String serviceCode,
        @WebParam(name = "codeScheme", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        int codeScheme,
        @WebParam(name = "ussdString", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String ussdString,
        @WebParam(name = "endPoint", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String endPoint,
        @WebParam(name = "extenionInfo", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        NamedParameterList extenionInfo)
        throws PolicyException, ServiceException
    ;

    /**
     * 
     * @param abortReason
     * @param receiveCB
     * @param senderCB
     * @param extenionInfo
     * @throws PolicyException
     * @throws ServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "sendUssdAbort", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", className = "org.csapi.schema.parlayx.ussd.send.v1_0.local.SendUssdAbort")
    @ResponseWrapper(localName = "sendUssdAbortResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", className = "org.csapi.schema.parlayx.ussd.send.v1_0.local.SendUssdAbortResponse")
    public void sendUssdAbort(
        @WebParam(name = "senderCB", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String senderCB,
        @WebParam(name = "receiveCB", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String receiveCB,
        @WebParam(name = "abortReason", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String abortReason,
        @WebParam(name = "extenionInfo", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        NamedParameterList extenionInfo)
        throws PolicyException, ServiceException
    ;

    /**
     * 
     * @param codeScheme
     * @param receiveCB
     * @param serviceCode
     * @param senderCB
     * @param extenionInfo
     * @param msIsdn
     * @param switchMode
     * @param ussdString
     * @return
     *     returns java.lang.String
     * @throws PolicyException
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
    @RequestWrapper(localName = "sendUssdSwitch", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", className = "org.csapi.schema.parlayx.ussd.send.v1_0.local.SendUssdSwitch")
    @ResponseWrapper(localName = "sendUssdSwitchResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local", className = "org.csapi.schema.parlayx.ussd.send.v1_0.local.SendUssdSwitchResponse")
    public String sendUssdSwitch(
        @WebParam(name = "senderCB", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String senderCB,
        @WebParam(name = "receiveCB", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String receiveCB,
        @WebParam(name = "SwitchMode", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        int switchMode,
        @WebParam(name = "msIsdn", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String msIsdn,
        @WebParam(name = "serviceCode", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String serviceCode,
        @WebParam(name = "codeScheme", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        int codeScheme,
        @WebParam(name = "ussdString", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        String ussdString,
        @WebParam(name = "extenionInfo", targetNamespace = "http://www.csapi.org/schema/parlayx/ussd/send/v1_0/local")
        NamedParameterList extenionInfo)
        throws PolicyException, ServiceException
    ;

}
